name: build and deploy springcrud-app to ecr
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: build and deploy springcrud-app to ecr
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: setup jdk 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17

    - name: unit tests
      run: mvn -B test --file pom.xml

    - name: build the app
      run: |
        mvn clean
        mvn -B package --file pom.xml
    - name: build the docker image
      uses: docker/build-push-action@v4
      with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/crud-app:latest
    
  

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: spring-crudapp
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY